# Generated by Django 5.0.1 on 2024-01-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('passport_details', models.IntegerField(max_length=10)),
            ],
        ),
    ]
