# Generated by Django 5.0.1 on 2024-01-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0008_alter_servicecost_end_alter_servicecost_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecost',
            name='end',
        ),
        migrations.RemoveField(
            model_name='servicecost',
            name='start',
        ),
    ]
