# Generated by Django 5.0.1 on 2024-01-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typography', '0009_remove_servicecost_end_remove_servicecost_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecost',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicecost',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
